language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: BNIDLNSl9MdyvPF41rN1uLfeCCYCyktB/rLCL4x4pLcLYg2OTmkLAbriuy7FZJb/H2brqVAqDgcZ55i1XXUIvE0QdEv7AfNW40njfzm4asUd6ts0SWlE/fXMmRRnbr19o/fPonu6Sa1lfZx4dnrZbvkarORU7IsHuOGnqn5fhpLkIewtrv1AMAe0Wtkggxvcz2w6TflSeNrrUjnpSAlZS+Jqv3e26Hm4Kdg56WrNVaQrBhB/b3Qy+6/jOOzveIFLtSA7TTaoUkgJ+83BJQsT5oZV3ecxe96d0eE8P418OlD1oDmYSEqoegwWdXlJw4yMfb+gawJIyyveDP0pc1UWBu0OOlB3jeuXStEBWARRAjiX3NCgh4P67i7Kc0t/0xrZ4Sg2JwiyToxtKwL/Btp41lYZauRBU7hthvSOaO0G7cgdwB94ASW0n6PtQ1ZlA9AtJDwa8MhJ/OIycGYIWSoRXJ2lUh1wN5RTPJc87RwaeWKVz1Qmz2SfmT0oYwImXMUFmvRaMbxV0JqfRMk46wp0aFXot9ZWbjc8IS4mZZBSThGFLGensJRuLWJXwlDzTZkafnxWeDODTWR34JoVN46plyu9ZU8IV9bNjrUUjOrBulCUEJF+mLt/KrnZETLao35wFhCJTrh2mEBIPDAIPXW9pe1uz/HmVfjgxCvWt1wnaP8=
  app: diecastr-api
  on:
    repo: davelarimore/diecastr-api
